name: MATLAB CI

on:
  push:
    branches: [main, Dev]
  pull_request:
    branches: [main, Dev]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run Process Advisor
        uses: matlab-actions/run-command@v1
        with:
          command: |
            % Open the project using relative path
            proj = openProject("D:\GIT\Matlab_1\Matlab\Add_Test.prj");

            % Load your Simulink model
            load_system("Models/Add_test");

            % Run Process Advisor
            advisorObj = Simulink.Check.ModelAdvisor.getModelAdvisor("Models/Add_test");
            advisorObj.run;

            % Export results
            advisorObj.exportResults("PA_Results/process_advisor_report.html");

            disp('Process Advisor completed in CI pipeline!');

      - name: Upload Process Advisor Report
        uses: actions/upload-artifact@v4
        with:
          name: process-advisor-report
          path: Matlab/Add_Test/PA_Results/process_advisor_report.html
